clc; clear; close all;

%% ================= USER-DEFINED SETTINGS =================
FIGURE_NAME = 'MFASMC Wall-Following Performance';

FIGURE_SIZE = [100 100 1200 800];   % [x y width height]

FONT_SIZE = 21;
FONT_NAME = 'Times New Roman';

TIME_LIMIT = [0 200];

% ---- Legend names (edit freely) ----
LEGEND_LEFT = {'Robot 1','Robot 2','Robot 3','Reference'};
LEGEND_XI   = {'\Xi_1','\Xi_2','\Xi_3'};

% ---- Line styles & colors (edit freely) ----
LINE_WIDTH = 1.8;

COLORS = [ ...
    0.00 0.45 0.74;   % blue
    0.85 0.33 0.10;   % orange
    0.47 0.67 0.19;   % green
];

REF_COLOR = [0 0 0];   % black
REF_STYLE = '--';

%% ================= DATA FILES =================
dataFolder = 'Dataplot';
dataFiles = { ...
    fullfile(dataFolder, 'robot1_mfasmc_data.csv'), ...
    fullfile(dataFolder, 'robot2_mfasmc_data.csv'), ...
    fullfile(dataFolder, 'robot3_mfasmc_data.csv') ...
};

%% ================= READ DATA =================
t_data = cell(1,3);
left_data = cell(1,3);
xi_data = cell(1,3);
desired_data = [];

for k = 1:length(dataFiles)
    T = readtable(dataFiles{k});
    t_data{k} = T{:,1};
    left_data{k} = T{:,2};
    xi_data{k} = T{:,5};
    if isempty(desired_data)
        desired_data = T{:,6};
    end
end

%% ================= CREATE FIGURE =================
figure('Name',FIGURE_NAME, ...
       'NumberTitle','off', ...
       'Position',FIGURE_SIZE);

%% ================= TOP SUBPLOT =================
ax1 = subplot(2,1,1); hold on; grid on;

for k = 1:3
    plot(t_data{k}, left_data{k}, ...
        'LineWidth', LINE_WIDTH, ...
        'Color', COLORS(k,:), ...
        'DisplayName', LEGEND_LEFT{k});
end

plot(t_data{1}, desired_data, ...
    'LineStyle', REF_STYLE, ...
    'Color', REF_COLOR, ...
    'LineWidth', LINE_WIDTH, ...
    'DisplayName', LEGEND_LEFT{4});

ylabel('Left Wall Distance (cm)', ...
    'FontSize', FONT_SIZE, ...
    'FontName', FONT_NAME);

xlim(TIME_LIMIT);

lgd1 = legend('show');
set(lgd1, ...
    'Orientation','horizontal', ...
    'Location','northoutside', ...
    'FontSize', FONT_SIZE-2, ...
    'FontName', FONT_NAME);

set(ax1, ...
    'FontSize', FONT_SIZE, ...
    'FontName', FONT_NAME, ...
    'LineWidth', 1.2);

%% ================= BOTTOM SUBPLOT =================
ax2 = subplot(2,1,2); hold on; grid on;

for k = 1:3
    plot(t_data{k}, xi_data{k}, ...
        'LineWidth', LINE_WIDTH, ...
        'Color', COLORS(k,:), ...
        'DisplayName', LEGEND_XI{k});
end

xlabel('Time (s)', ...
    'FontSize', FONT_SIZE, ...
    'FontName', FONT_NAME);

ylabel('Distributed Error $\Xi$', ...
    'Interpreter','latex', ...
    'FontSize', FONT_SIZE, ...
    'FontName', FONT_NAME);

xlim(TIME_LIMIT);

lgd2 = legend('show');
set(lgd2, ...
    'Orientation','horizontal', ...
    'Location','southoutside', ...
    'FontSize', FONT_SIZE-2, ...
    'FontName', FONT_NAME);

set(ax2, ...
    'FontSize', FONT_SIZE, ...
    'FontName', FONT_NAME, ...
    'LineWidth', 1.2);
